Updated 'tkinter' askopenfile method use to fix bug
'tkinter' askopenfile() requires -filetypes (not -filetype) to run code

Bug below:
File "/home/runner/Python/main.py", line 87, in checker
    fileNameCombo = filedialog.askopenfile(parent=root, mode='rb', title='Choose your combo',filetype=(("txt", "*.txt"), ("All files", "*.txt")))

s = master.tk.call(self.command, *master._options(self.options))
_tkinter.TclError: bad option "-filetype": must be -defaultextension, -filetypes, -initialdir, -initialfile, -multiple, -parent, -title, or -typevariable